# fly.toml app configuration file generated for personal-manager-s3tq-q on 2025-09-14T11:37:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'personal-manager-s3tq-q'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
